---
title: "preparacion_df"
format: html
editor: visual
---

# Librería utilizadas

```{r}
library(tidyverse)
```

# Cargado de datos

```{r}
df_og <- read_csv("listings_bcn.csv")
```

# Limpieza de datos

## Selección de variables

```{r}
df <- df_og |>
  select(id, 
         name, # A pesar de que no es cualitativo, nos sirve para identificar al piso
         neighbourhood_group_cleansed,
         latitude,
         longitude,
         room_type,
         accommodates,
         bathrooms_text,
         bedrooms,
         beds,
         price,
         minimum_nights,
         maximum_nights,
         has_availability,
         availability_30,
         availability_60,
         availability_90,
         availability_365,
         number_of_reviews,
         number_of_reviews_ltm,
         number_of_reviews_l30d,
         review_scores_rating,
         review_scores_accuracy,
         review_scores_cleanliness,
         review_scores_checkin,
         review_scores_communication,
         review_scores_location,
         review_scores_value
         ) 
```

## Limpieza de las variables

### bathroom_text

```{r}
unique(df$bathrooms_text)

df$bathrooms_text <- ifelse(df$bathrooms_text == "Shared half-bath", "0.5 Shared bath",
                            ifelse(df$bathrooms_text == "Private half-bath", "0.5 bath",
                            ifelse(df$bathrooms_text == "Half-bath", "0.5 bath", df$bathrooms_text)))

df$shared_bathrooms <- grepl("shared|Shared", df$bathrooms_text)

df$n_bathrooms <- sapply(strsplit(df$bathrooms_text, " "), function(x) as.numeric(x[1]))

bathrooms_text_position <- which(colnames(df) == "bathrooms_text")

df <- df %>%
  relocate(all_of(c("n_bathrooms", "shared_bathrooms")), .before = bathrooms_text_position)


df <- df %>%
  select(-bathrooms_text)

rm(bathrooms_text_position)
```

### price

```{r}
df$price <- as.numeric(gsub("\\$", "", df$price))
```

### review_score_rating

```{r}
df$review_scores_rating <- ifelse(df$review_scores_rating == 0, NA, df$review_scores_rating)
```

## Ajuste tipos de datos de las variables

```{r}
df <- df %>%
  mutate(
    neighbourhood_group_cleansed = factor(neighbourhood_group_cleansed),
    room_type = factor(room_type)
  )
```

## Renombre de columnas

```{r}
df_es <- df |>
  select(id, 
         nombre = name, 
         barrio = neighbourhood_group_cleansed,
         latitud = latitude,
         longitud = longitude,
         tipo_propiedad = room_type,
         capacidad = accommodates,
         banos = n_bathrooms,
         bano_compartido = shared_bathrooms,
         dormitorios = bedrooms,
         camas = beds,
         precio = price,
         noches_minimas = minimum_nights,
         noches_maximas = maximum_nights,
         disponible = has_availability,
         disponibilidad_30 = availability_30,
         disponibilidad_60 = availability_60,
         disponibilidad_90 = availability_90,
         disponibilidad_365 = availability_365,
         n_reviews = number_of_reviews,
         n_reviews_u30d = number_of_reviews_l30d,
         puntuacion_reviews_general = review_scores_rating,
         puntuacion_reviews_precision = review_scores_accuracy,
         puntuacion_reviews_limpieza = review_scores_cleanliness,
         puntuacion_reviews_checkin = review_scores_checkin,
         puntuacion_reviews_comunicacion = review_scores_communication,
         puntuacion_reviews_localizacion = review_scores_location,
         puntuacion_reviews_valor = review_scores_value 
         ) 
```

# Guardado de archivo

```{r}
saveRDS(df, "clean_airbnb_data.rds")
```
